# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_EditTableTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QAbstractItemView

import repository
import utility
from UI_AcceptDialog import UI_AcceptDialog


class UI_EditTableTemplate(QWidget):
    def __init__(self, widget):
        super().__init__()
        self.setObjectName("Dialog")
        self.resize(820, 480)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 360, 61, 16))
        self.label.setObjectName("label")
        self.outputConsole = QtWidgets.QTextBrowser(self)
        self.outputConsole.setEnabled(True)
        self.outputConsole.setGeometry(QtCore.QRect(40, 380, 611, 61))
        self.outputConsole.setObjectName("outputConsole")
        self.tableNameDropdown = QtWidgets.QComboBox(self)
        self.tableNameDropdown.setGeometry(QtCore.QRect(690, 40, 121, 22))
        self.tableNameDropdown.setObjectName("tableNameDropdown")
        self.tableNameDropdown.addItem("")
        self.tableNameDropdown.addItem("")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(690, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.generateDataButton = QtWidgets.QToolButton(self)
        self.generateDataButton.setGeometry(QtCore.QRect(690, 280, 121, 41))
        self.generateDataButton.setStyleSheet("background-color: rgb(0, 220, 0);")
        self.generateDataButton.setObjectName("generateDataButton")
        self.clearDatabaseButton = QtWidgets.QToolButton(self)
        self.clearDatabaseButton.setGeometry(QtCore.QRect(690, 330, 121, 41))
        self.clearDatabaseButton.setStyleSheet("background-color: rgb(220, 0, 0);")
        self.clearDatabaseButton.setObjectName("clearDatabaseButton")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.backToMenuButton = QtWidgets.QPushButton(self)
        self.backToMenuButton.setGeometry(QtCore.QRect(690, 380, 121, 61))
        self.backToMenuButton.setObjectName("backToMenuButton")
        self.table = QtWidgets.QTableWidget(self)
        self.table.setGeometry(QtCore.QRect(40, 40, 611, 311))
        self.table.setAutoFillBackground(False)
        self.table.setObjectName("table")
        self.table.setColumnCount(16)
        self.table.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(15, item)
        #self.addNewFieldButton = QtWidgets.QPushButton(self)
        #self.addNewFieldButton.setGeometry(QtCore.QRect(690, 210, 121, 31))
       # self.addNewFieldButton.setObjectName("addNewFieldButton")
        self.removeFieldButton = QtWidgets.QPushButton(self)
        self.removeFieldButton.setGeometry(QtCore.QRect(690, 240, 121, 31))
        self.removeFieldButton.setObjectName("removeFieldButton")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(690, 152, 47, 13))
        self.label_5.setObjectName("label_5")
        self.peselSearch = QtWidgets.QLineEdit(self)
        self.peselSearch.setGeometry(QtCore.QRect(690, 101, 119, 20))
        self.peselSearch.setInputMask("")
        self.peselSearch.setText("")
        self.peselSearch.setMaxLength(6)
        self.peselSearch.setObjectName("peselSearch")
        self.insertField = QtWidgets.QLineEdit(self)
        self.insertField.setGeometry(QtCore.QRect(690, 176, 119, 20))
        self.insertField.setText("")
        self.insertField.setObjectName("nameSearch")
        self.updateField = QtWidgets.QLineEdit(self)
        self.updateField.setGeometry(QtCore.QRect(690, 203, 119, 20))
        self.updateField.setText("")
        self.updateField.setObjectName("surnameSearch")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(690, 80, 119, 10))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_4.setObjectName("label_4")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.clearDatabaseButton.clicked.connect(lambda: self.showAcceptDialog(self.clearDatabase, "Clear database"))
        self.generateDataButton.clicked.connect(lambda: self.showAcceptDialog(self.generateDatabase, "Generate new data"))
        self.removeFieldButton.clicked.connect(lambda: self.showAcceptDialog(self.deleteSelectedRecords, "Delete record"))

        self.peselSearch.editingFinished.connect(
            lambda: repository.apply_search(self.table, self.tableNameDropdown.currentText(), 'PESEL',
                                            self.peselSearch))
        self.insertField.editingFinished.connect(self.add_data)
        self.updateField.editingFinished.connect(self.update_data)

        self.backToMenuButton.clicked.connect(self.gotoMenu)
        self.tableNameDropdown.currentTextChanged.connect(self.initFromDatabase)

        repository.outputlog = self.outputConsole
        self.parent = widget
        self.initFromDatabase()

    def add_data(self):
        insert_msg = self.insertField.text()
        if insert_msg == '':
            return
        repository.insert_data(self.tableNameDropdown.currentText(), insert_msg)
        repository.load_table_structure(self.table, str(self.tableNameDropdown.currentText()))


    def update_data(self):
        update_msg = self.updateField.text()
        if update_msg == '':
            return
        repository.update_data(self.tableNameDropdown.currentText(), update_msg)
        repository.load_table_structure(self.table, str(self.tableNameDropdown.currentText()))

    def initFromDatabase(self):
        repository.load_table_structure(self.table, str(self.tableNameDropdown.currentText()))

    def gotoMenu(self):
        self.parent.setCurrentIndex(0)

    def showAcceptDialog(self, func, name):
        acceptDialog = UI_AcceptDialog()
        acceptDialog.setObjectName(name)
        retValue = acceptDialog.exec_()
        if retValue == QtWidgets.QDialog.Accepted:
            func()

    def deleteSelectedRecords(self):
        index_list = []
        for model_index in self.table.selectionModel().selectedRows():
            index = QtCore.QPersistentModelIndex(model_index)
            index_list.append(index)

        for index in index_list:
            self.deleteRecord(index)
        repository.load_table_structure(self.table, str(self.tableNameDropdown.currentText()))

    def deleteRecord(self, index):
        # self.table.removeRow(index.row()) send msg to database
        tablename = str(self.tableNameDropdown.currentText())

        column_pesel_ind=0
        if tablename == 'STUDENCI_PR':
            column_pesel_ind = 1
        else:
            column_pesel_ind = 2

        print(index.column(), index.row())
        pesel = self.table.item(index.row(), index.column() + column_pesel_ind).text()
        repository.remove_data(tablename, 'PESEL={}'.format(pesel))


    def generateDatabase(self):
        self.clearDatabase()
        utility.insert_const_data()
        utility.insert_data_for_dictionaries()
        utility.generate_data_for_table("ROKI", 5)
        print("roki")
        utility.generate_data_for_table("SEMESTRY", 10)
        print('semestry')
        utility.generate_data_for_table("PRZEDMIOTY_PR", 35)
        print('przedmioty')
        utility.generate_data_for_table("STUDENCI_PR", 100)
        print('studenci_pr')
        utility.generate_data_for_table("PRAC_UCZELNI", 25)
        print('prac-ucz')
        repository.load_table_data(self.table, str(self.tableNameDropdown.currentText()))
        self.outputConsole.append("Generated data ...")

    def clearDatabase(self):
        repository.remove_all_data('STUDENCI_PR')
        repository.remove_all_data('PRAC_UCZELNI')
        repository.remove_all_data('STATUSY')
        repository.remove_all_data('TYTULY')
        repository.remove_all_data('STANOWISKA')
        repository.remove_all_data('OCENY_PR')
        repository.remove_all_data('PRZEDMIOTY_PR')
        repository.remove_all_data('SEMESTRY')
        repository.remove_all_data('ROKI')
        repository.remove_all_data('KIERUNKI')
        repository.remove_all_data('WYDZIALY')
        repository.load_table_data(self.table, str(self.tableNameDropdown.currentText()))
        self.outputConsole.append("Data is cleared ...")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Output log:"))
        self.outputConsole.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tableNameDropdown.setItemText(0, _translate("Dialog", "STUDENCI_PR"))
        self.tableNameDropdown.setItemText(1, _translate("Dialog", "PRAC_UCZELNI"))
        self.label_2.setText(_translate("Dialog", "Select table:"))
        self.generateDataButton.setText(_translate("Dialog", "Generate example data"))
        self.clearDatabaseButton.setText(_translate("Dialog", "Clear database"))
        self.label_3.setText(_translate("Dialog", "Table content:"))
        self.backToMenuButton.setText(_translate("Dialog", "Back to menu"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "PESEL"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "imię"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "nazwisko"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "płeć"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "adres"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "data_urodzenia"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "narodowość"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "telefon"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "data_rekrutacji"))
        item = self.table.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "data_zakończenia"))
        item = self.table.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "status"))
        item = self.table.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "grupa_dziekańska"))
        item = self.table.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "bieżące_punkty_ECTS"))
        item = self.table.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "średnia_z_ocen"))
        item = self.table.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "semestry_id_semestru"))
        item = self.table.horizontalHeaderItem(15)
        item.setText(_translate("Dialog", "narodowość"))
       #self.addNewFieldButton.setText(_translate("Dialog", "Apply"))
        self.removeFieldButton.setText(_translate("Dialog", "Remove"))
        self.label_5.setText(_translate("Dialog", "Actions:"))
        self.peselSearch.setPlaceholderText(_translate("Dialog", "PESEL"))
        self.insertField.setPlaceholderText(_translate("Dialog", "Insert record: <arg1, arg2, ...>"))
        self.updateField.setPlaceholderText(_translate("Dialog", "Update record: SET <> WHERE <>"))
        self.label_4.setText(_translate("Dialog", "Search:"))
