# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ErrorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class UI_ErrorDialog(QDialog):
    def __init__(self, errorType, errorText):
        super().__init__()
        self.setObjectName("Dialog")
        self.resize(240, 195)
        self.errorMessage = QtWidgets.QLabel(self)
        self.errorMessage.setGeometry(QtCore.QRect(40, 60, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.errorMessage.setFont(font)
        self.errorMessage.setObjectName("errorMessage")
        self.okButton = QtWidgets.QPushButton(self)
        self.okButton.setGeometry(QtCore.QRect(80, 140, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.okButton.clicked.connect(self.accept)

        self.retranslateUi(errorType, errorText)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, errorType, errorText):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.errorMessage.setText(_translate("Dialog", "ERROR {}:\n{}".format(errorType, errorText)))
        self.okButton.setText(_translate("Dialog", "OK"))
