# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

import repository
from UI_AuthentificationDialog import UI_AuthentificationDialog
from UI_EditTableTemplate import UI_EditTableTemplate
from UI_ViewTableTemplate import UI_ViewTableTemplate

class UI_MainMenu(QMainWindow):
    def __init__(self, widget):
        super().__init__()
        self.setObjectName("MainMenu")
        self.resize(820, 484)
        self.exploreButton = QtWidgets.QToolButton(self)
        self.exploreButton.setGeometry(QtCore.QRect(240, 110, 351, 61))
        self.exploreButton.setObjectName("exploreButton")
        self.editButton = QtWidgets.QToolButton(self)
        self.editButton.setGeometry(QtCore.QRect(240, 200, 351, 61))
        self.editButton.setObjectName("editButton")
        self.exitButton = QtWidgets.QToolButton(self)
        self.exitButton.setGeometry(QtCore.QRect(240, 290, 351, 61))
        self.exitButton.setObjectName("exitButton")

        self.exploreButton.clicked.connect(self.gotoExplore)
        self.editButton.clicked.connect(self.gotoEdit)
        self.exitButton.clicked.connect(self.exitApp)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.view = None
        self.edit = None
        self.parent = widget

        # Authorization
        self.showAuthorizationDialog()

    def showAuthorizationDialog(self):
        authDialog = UI_AuthentificationDialog()
        retValue = authDialog.exec_()
        if retValue == QtWidgets.QDialog.Accepted:
            pass
        else:
            exit(0)


    def gotoExplore(self):
        if self.view is None:
            self.view = UI_ViewTableTemplate(self.parent)
        self.parent.addWidget(self.view)

        add = 1
        if (self.parent.count() > 2):
            add = 2
        self.parent.setCurrentIndex(self.parent.currentIndex() + add)

    def gotoEdit(self):
        if self.edit is None:
            self.edit = UI_EditTableTemplate(self.parent)
        self.parent.addWidget(self.edit)

        add = 1
        if (self.parent.count() > 2):
            add = 2
        self.parent.setCurrentIndex(self.parent.currentIndex() + add)

    def exitApp(self):
        if (repository.cnxn != None):
            repository.cnxn.commit()
            repository.cnxn.close()
        exit(0)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.exploreButton.setText(_translate("Form", "Explore database"))
        self.editButton.setText(_translate("Form", "Edit database"))
        self.exitButton.setText(_translate("Form", "Exit"))
